on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@v5
      with:
        baseUri: "https://sguduru-gonfalon.ngrok.io"
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
        projKey: default
